# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Release

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: central # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
    - name: Release
      uses: qcastel/github-actions-maven-release@master
      env:
        GITHUB_TOKEN: ${{ github.token }}
        MAVEN_USERNAME: ${{ secrets.MVNCENTRAL_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MVNCENTRAL_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        git-release-bot-name: "release-bot"
        git-release-bot-email: "release-bot@m-idea.net"
        release-branch-name: "master"
        gpg-enabled: "true"
        gpg-key-id: ${{ secrets.BOT_GPG_KEY_ID }}
        gpg-key: ${{ secrets.BOT_GPG_KEY }}